#!/bin/bash
set -Eeuo pipefail

GID=$(id -g)
VERSION="dev"

BUCEE_HOME=$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")
COMMAND="$1"

case "$COMMAND" in
build)
  podman build -t localhost/bucee:$VERSION \
    --build-arg=USER=$USER \
    --build-arg=UID=$UID \
    --build-arg=GID=$GID \
    -f $BUCEE_HOME/Containerfile
  ;;

go)
  podman rm -f bucee

  # --user, --userns: Align host and container user 
  # --network=host: Use the host's network namespace to simplify container to host and
  # container to container traffic
  # -v bucee_home:/home/$USER: Persist user home in a named volume
  # -v $HOME/xxx: Share some of the user home directories
  # podman.sock: Allow container to use rootless podman of the host via Unix socket
  podman run -d \
    --name bucee \
    --hostname bucee \
    --restart=always \
    --tz=local \
    --user $UID:$GID \
    --userns=keep-id:uid=$UID,gid=$GID \
    --network=host \
    -v bucee_home:/home/$USER \
    -v $HOME/.gitconfig:/home/$USER/.gitconfig \
    -v $HOME/.ssh:/home/$USER/.ssh \
    -v $HOME/repos:/home/$USER/repos \
    -v $XDG_RUNTIME_DIR/podman/podman.sock:/run/user/$UID/podman/podman.sock \
    -e CONTAINER_HOST=unix:///run/user/$UID/podman/podman.sock \
    -e DOCKER_HOST=unix:///run/user/$UID/podman/podman.sock \
    --security-opt label=disable \
    localhost/bucee:$VERSION
  ;;

shell)
  podman exec -ti bucee /bin/fish
  ;;

rootshell)
  podman exec -ti -u root bucee /bin/fish
  ;;

*)
  echo -e "Bucee: unknown command $1"
  ;;

esac
